services:
  dynamodb:
    build: ./local-dynamodb
    volumes:
      - dynamodb-data:/data
    ports:
      - 8000:8000

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000

volumes:
  dynamodb-data:
