[source."git+https://github.com/cipherstash/ore.rs"]
git = "https://github.com/cipherstash/ore.rs"
replace-with = "vendored-sources"

[source."git+ssh://git@github.com/cipherstash/cipherstash-suite.git?branch=feat/compound-spike"]
git = "ssh://git@github.com/cipherstash/cipherstash-suite.git"
branch = "feat/compound-spike"
replace-with = "vendored-sources"

[source."git+ssh://git@github.com/cipherstash/vitur-rs.git?branch=main"]
git = "ssh://git@github.com/cipherstash/vitur-rs.git"
branch = "main"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
