name: "Test Rust"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

env:
  CARGO_REGISTRIES_CIPHERSTASH_TOKEN: "Token ${{ secrets.CLOUDSMITH_CARGO_TOKEN }}"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      dynamo:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000

    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: "Run tests"
        run: cargo test --all-targets
        env:
          CS_WORKSPACE_ID: ${{ secrets.CS_WORKSPACE_ID }}
          CS_CLIENT_ACCESS_KEY: ${{ secrets.CS_CLIENT_ACCESS_KEY }}
          CS_CLIENT_ID: ${{ secrets.CS_CLIENT_ID }}
          CS_CLIENT_KEY: ${{ secrets.CS_CLIENT_KEY }}
          CS_VITUR_IDP_HOST: "https://ap-southeast-2.aws.auth.viturhosted.net"
          AWS_ACCESS_KEY_ID: cipherstash-dynamodo
          AWS_SECRET_ACCESS_KEY: cipherstash-dynamodo
          AWS_REGION: ap-southeast-2
          RUST_BACKTRACE: full

      - name: "Run doc tests"
        run: cargo test --doc
        env:
          RUST_BACKTRACE: full

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - run: cargo clippy --all --no-deps --all-features --tests
